### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Helehelehele** [Helehelehele/melloutbot#2]
This still needs a lot of work, so I'm going to list as much as I can remember now.

- [ ] Handle rest of the "basic" events.
- [ ] Implement [rate limits](https://dev.twitch.tv/docs/irc/guide/#command--message-limits).
- [ ] Add a way to remove event handlers.
- [ ] Implement a channel cache. (This is a maybe)
- [ ] Actually implement the command handler.
- [ ] Check for connection states.
- [ ] Implement logging.
- [ ] Implement [IRC commands](https://dev.twitch.tv/docs/irc/guide/#scopes-for-irc-commands).
- [ ] Implement [Membership Capability](https://dev.twitch.tv/docs/irc/membership/).
- [ ] Implement [Tags Capability](https://dev.twitch.tv/docs/irc/tags/).
- [ ] Implement [Commands Capability](https://dev.twitch.tv/docs/irc/commands/).
- [ ] Implement [Chat Rooms Capability](https://dev.twitch.tv/docs/irc/chat-rooms/).

I don't see a point in implementing any of the REST API or PubSub so far, hence I will ignore their existence.
